[FIX] mail: don't try to get id of None in assertNoMail test method
Regression of https://github.com/odoo/odoo/pull/230766

Fixes
```
2023-01-02 10:00:00,000 253111 ERROR odoo odoo.addons.mail_post_defer.tests.test_mail: ERROR: MessagePostCase.test_queued_msg_delete
Traceback (most recent call last):
  File "/home/odoo/odoo/18.0/mail/mail_post_defer/tests/test_mail.py", line 145, in test_queued_msg_delete
    self.assertNoMail(
  File "/home/odoo/odoo/18.0/odoo/addons/mail/tests/common.py", line 753, in assertNoMail
    self.assertNotSentEmail(recipients=recipients, message_id=mail_message.message_id)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'message_id'
```